import './globals.scss'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { FC, ReactNode } from 'react'
import Footer from '@/Components/Footer/Footer'
import Header from '@/Components/Header/Header'


const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProp = {
  children:ReactNode
}

const RootLayout:FC<LayoutProp> = ({children})=> {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main >
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  )
}
export default RootLayout
